### ISSUE TITLE
available roles blank

### ISSUE THREAD

**Issue by igalmk** [ofirlevy1/Stepper#110]
a blank role appears in available roles(maybe manager?)

**Comment by ofirlevy1** [comment]
Looking at a simple example using postman, it seems fine:

![image](https://github.com/ofirlevy1/Stepper/assets/96801187/78bbe167-bcb0-4dc7-a095-d45f39605558)

could this be a problem on the client's side?

**Comment by igalmk** [comment]
will check about it
