### ISSUE TITLE
run flow servlet reconfiguration

### ISSUE THREAD

**Issue by igalmk** [ofirlevy1/Stepper#117]
if able ,to make the run_flow servlet to return the latest flowRunHistory, i.e of the flow that just ran

**Comment by ofirlevy1** [comment]
The flow execution is asynchronous - the servlet that runs it, simply calls the "flow.execute" command and returns immediately - it doesn't wait for the flow to finish. 

What if I'll do a "GetFlowRunHistory" servlet that gets the flowID (which you get from run_flow servlet) and returns the history?

**Comment by igalmk** [comment]
yea i can do that

**Comment by ofirlevy1** [comment]
but actually you'll need to make sure the flow has finished executing before pulling it's history.

maybe ill do another servlet for that?  /is_flow_running ?

**Comment by igalmk** [comment]
like a status? that could work well

**Comment by ofirlevy1** [comment]
I added an "**has_flow_failed**" servlet since that's how it was done in assignment 2. Thought it'd be more comfortable for you.

**Comment by ofirlevy1** [comment]
Done - added the "**/flow_run_history**" servlet as well.
