### ISSUE TITLE
manager not set upon user creation

### ISSUE THREAD

**Issue by igalmk** [ofirlevy1/Stepper#120]
when a new user is created, his manager status is not set

**Comment by ofirlevy1** [comment]
Looks like it should be, this is the (only) constructor of "User": 

![image](https://github.com/ofirlevy1/Stepper/assets/96801187/1049c403-136c-427e-a1d4-be82ea2b8938)

How did you figure that it's not set?

**Comment by igalmk** [comment]
my bad,it was a visual bug that show blank and me think that manager wa not set
