### ISSUE TITLE
In "Available Flows", same flow can appear multiple times (for each of the user's roles that have that flow)

### ISSUE THREAD

**Issue by ofirlevy1** [ofirlevy1/Stepper#128]
![image](https://github.com/ofirlevy1/Stepper/assets/96801187/a99c6580-e465-4bcd-bba9-80c6d4fe5df9)

**Comment by igalmk** [comment]
![Screenshot 2023-07-25 075420](https://github.com/ofirlevy1/Stepper/assets/94670379/a0e57c9d-6315-4024-8771-1f7436a8ec4c)

strange, for me it works fine

**Comment by ofirlevy1** [comment]
fixed
