### ISSUE TITLE
flow status "remembers" last execution

### ISSUE THREAD

**Issue by igalmk** [ofirlevy1/Stepper#133]
when reruning a flow, the flow status that is sent in response from the flow status servlet is already "warning", and not "running", 
need to further check when switching for flow execution to other flow execution if the problem persists, also check in case of "succes" and "failure"

**Comment by igalmk** [comment]
also i checked if i was running the same flow(flow id), but no, i got the same for different flow

**Comment by igalmk** [comment]
and i checked it on flow that has spend some time step, that flow should have had hte "running" status for a few seconds

**Comment by ofirlevy1** [comment]
I did some change there. can you check again? (with the updated WAR I'll send you)

**Comment by igalmk** [comment]
for some reason, flow status servlet still returns "warning" instead of "running" from second execution and on
